#!/bin/bash

CALDIR=$HOME/$DATA_DIR/cal
CALFILE=cal-week
gcalcli --cal Ethan --cal 'Family Shared' --cal "US Holidays" --width=21 calw > $CALDIR/$CALFILE.tmp
if [ $? -eq 0 ]
then
	rm $CALDIR/$CALFILE.txt
	mv $CALDIR/$CALFILE.tmp $CALDIR/$CALFILE.txt
else
	rm $CALDIR/$CALFILE.tmp
	echo -n "*" >> $CALDIR/$CALFILE.txt
fi
