#!/bin/bash

CALDIR=$HOME/$DATA_DIR/cal
CALFILE=cal-month.txt
cat $CALDIR/$CALFILE
HOURS_SINCE_UPDATE=$(((`date --utc +%s`-`date --utc --reference=$CALDIR/$CALFILE +%s`)/60/60))
if [ "$HOURS_SINCE_UPDATE" -gt "0" ]
then
echo -n "$HOURS_SINCE_UPDATE hours since last update "
fi
sleep 30
