#!/bin/bash

# takes three values: on duration, off duration, cycles

for i in `seq 1 $3`
do
    echo 0 > /sys/class/leds/tpacpi\:\:power/brightness
    sleep $1
    echo 0 > /sys/class/leds/tpacpi\:\:thinkvantage/brightness
    sleep $2
done

