#!/bin/bash

. $HOME/.profile

PID=`pgrep msmtp`
MAILQUEUE=$HOME/$DATA_DIR/mail/queue
QUEUECOUNT=`ls $MAILQUEUE | wc -l`

[[ -n "$PID" ]] && exit 1

if [ $QUEUECOUNT -gt 0 ]
then
msmtpq -r &>/dev/null &
logger "cron-send-mailqueue run"
fi

exit 0
