#!/bin/bash

#tar -czvf $HOME/backups/home-$(date +%F).tar.gz $HOME
sudo tar -czvf $HOME/tmp/etc-$(date +%F).tar.gz /etc
sudo tar -czvf $HOME/tmp/usr-local-bin-$(date +%F).tar.gz /usr/local/bin
scp $HOME/tmp/*-$(date +%F).tar.gz es@10.7.7.51:

