#!/bin/bash
volt=`cat /proc/acpi/battery/BAT0/state | grep -i "present voltage" | awk '{print $3}'`
ampere=`cat /proc/acpi/battery/BAT0/state | grep -i "present rate" | awk '{print $3}'`
volt=`echo "scale=3;$volt/1000"|bc`
ampere=`echo "scale=3;$ampere/1000"|bc`
echo "Present voltage: " $volt "Volt"
echo "Present current: " $ampere "Ampere"
power=`echo "scale=3;$volt*$ampere"|bc`
#power=${power/.*}
echo "Present power   :" $power "Watt"
