#!/bin/sh

# Prints volume changes to stdout.  
# Depends on inotify-tools package

SOUND_DEV="/dev/snd/controlC0"

volume() {
	CURRENT_VOL=$(amixer -D default sget Master,0 | grep -m 1 "\[on\]" | cut -f 7 -d " " | sed -e's/\[//g' -e 's/%\]//g') 
	if [ $CURRENT_VOL ]; then
		echo $CURRENT_VOL
	else
		echo "-1"
	fi
}

# loop only runs when inotify didn't fail (not present on all systems)
# and when parent process is xmobar.  this _should_ ensure script quits after xmonad resets

while [ $? -eq 0 ]; # && [[  $(ps p $PPID | grep xmobar) ]]; 
do
	volume
	inotifywait $SOUND_DEV -e ACCESS -e CLOSE_WRITE > /dev/null 2>/dev/null
done
