#!/bin/bash

if [ "`cat /var/run/pm-utils/pm-powersave/state`" = "true" ]; then POWERMODE=MIN; else POWERMODE=MAX; fi

echo -n "<fc=#b58900>${powermode}</fc>"

AC_ONLINE=`cat /sys/class/power_supply/AC/online`

battery_info()
{
    BATTERY=$1
    if [ -f $BATTERY/energy_now ]; then
        PWR_PREFIX=energy
        if [ -f $BATTERY/power_now ]; then
            # should be reporting in ?
            DRAW_PREFIX=power
        else
            # should be reporting in milliwatts?
            DRAW_PREFIX=current
        fi
        DIVISOR=10
    else
        # should be reporting in milliamps?
        PWR_PREFIX=charge
        DRAW_PREFIX=current
        DIVISOR=1
    fi
    PWR_DRAW=`cat $BATTERY"/"$DRAW_PREFIX"_now"`
    PWR_NOW=`cat $BATTERY"/"$PWR_PREFIX"_now"`
    PWR_MAX=`cat $BATTERY"/"$PWR_PREFIX"_full"`
    PWR_AMPS=`cat "$BATTERY/current_now"`
    PWR_VOLTS=`cat "$BATTERY/voltage_now"`
}

TOTAL_PWRMAX=0
TOTAL_PWRNOW=0
TOTAL_TIME=0
TOTAL_PERCENT=0
MAX_PERCENT=0

for battery in /sys/class/power_supply/BAT*; do
#battery=/sys/class/power_supply/BAT1
battery_info $battery
    TOTAL_PWRMAX=`echo "$TOTAL_PWRMAX+($PWR_MAX/$DIVISOR)" | bc`
    TOTAL_PWRNOW=`echo "$TOTAL_PWRNOW+($PWR_NOW/$DIVISOR)" | bc`
    if [ $PWR_DRAW -gt 0 ]; then
        TOTAL_PWRDRAW=`echo "($PWR_DRAW/$DIVISOR)" | bc`
        #volts=`echo "scale=3;$PWR_VOLTS/1000"|bc`
        #amps=`echo "scale=3;$PWR_AMPS/1000"|bc`
        #WATTS=`echo "scale=3;$volts*$amps"|bc`
        #WATTS=${WATTS/.*}
    fi
done
#WATTS=printf $3*.001}' | sed -n 's/^\(.*\..\).*/\1/p'`
WATTS=`echo "($TOTAL_PWRDRAW/100000)" | bc`
WATTS=`printf "%.*f" 1 $WATTS`

CHARGE_REMAINING=`echo "scale=2; ($TOTAL_PWRNOW/$TOTAL_PWRMAX)*100" | bc`
CHARGE_REMAINING=${CHARGE_REMAINING/.*}
TIME_REMAINING=`echo "scale=2;($TOTAL_PWRNOW/$TOTAL_PWRDRAW)*60" | bc`
HOURS_REMAINING=`echo "scale=0;($TIME_REMAINING/60)" | bc`
MINUTES_REMAINING=`echo "scale=0;($TIME_REMAINING%60)" | bc`
MINUTES_REMAINING=${MINUTES_REMAINING/.*}

BATT_TIME=`printf "%i:%02i\n" $HOURS_REMAINING $MINUTES_REMAINING`

if [ $AC_ONLINE -eq 1 ]; then
    AC_PREFIX="AC:++"
    BATT_TIME=""
else
    AC_PREFIX="Batt:--"
    BATT_TIME=" $BATT_TIME"
fi

if [ $CHARGE_REMAINING -gt 70 ]; then
    BATT_COLOR="#719e07"
elif [ $CHARGE_REMAINING -gt 30 ]; then
    BATT_COLOR="#b58900"
else
    BATT_COLOR="#dc322f"
fi

echo "<fc=$BATT_COLOR>$POWERMODE $AC_PREFIX$CHARGE_REMAINING%$BATT_TIME $WATTS W </fc>"

